### PR TITLE
Add a build that tests against Redis 4

### LINKED ISSUE #197: Add Redis 4.0 to tests
> Redis 4.0 was released as GA in July 2017

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #197
Previously #198

### CODE REVIEW

**Comment by szepeviktor** [comment]
You're welcome.

Is `REDIS_VERSION` a Travis secret? No traces in Google.

**Comment by danielbachhuber** [comment]
> Is `REDIS_VERSION` a Travis secret? No traces in Google.

Nope, simply something I used to apply your installation logic.

**Comment by szepeviktor** [comment]
Seems like you declare it and there is no reference to it.
Maybe I am wrong.

**Comment by danielbachhuber** [comment]
Ah, you are correct: #215

**Pull request merged**
