### PR TITLE
Introduce `wp redis info` for basic Redis connection details

### PR DESCRIPTION
**Pull request by danielbachhuber**
```
salty-wordpress ➜  wp-redis  wp redis info
+-------------------+-----------+
| Field             | Value     |
+-------------------+-----------+
| status            | connected |
| used_memory       | 531.16K   |
| uptime            | 0 days    |
| key_count         | 21        |
| instantaneous_ops | 9/sec     |
| lifetime_hitrate  | 60%       |
| redis_host        | 127.0.0.1 |
| redis_port        | 6379      |
| redis_auth        |           |
| redis_database    | 0         |
+-------------------+-----------+
```

See #117

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@stevector #reviewmerge

**Comment by danielbachhuber** [comment]
@stevector Oh, and here's the dump from `$redis->info()` if there's anything else you think is worth including: https://gist.github.com/danielbachhuber/030917c180b0fdfe3946c69873b3c140

**Comment by stevector** [comment]
How can/should we test this feature?

**Comment by danielbachhuber** [comment]
> How can/should we test this feature?

We'd need to include WP-CLI's Behat test suite too, and then write some tests.

Or, we could abstract the logic of the `info()` method to a helper function, use the helper function instead, and write tests around it.

**Comment by stevector** [comment]
Which do you suggest?

**Comment by danielbachhuber** [comment]
> Which do you suggest?

The latter is much easier to do 86ac8ee

**Comment by stevector** [comment]
I'm getting an odd output message when running through terminus


```
terminus wp  "redis info"
[2016-08-23 14:46:11] [info] Running wp redis info on stevector-redis
    cmd: 'redis info'
    site: 'stevector'
    env: 'redis'
tput: No value for $TERM and no -T specified
+-------------------+----------------------------------+
| Field             | Value                            |
+-------------------+----------------------------------+
| status            | connected                        |
| used_memory       | 1015.73K                         |
| uptime            | 117 days                         |
| key_count         | 4                                |
| instantaneous_ops | 4/sec                            |
| lifetime_hitrate  | 70.65%                           |
| redis_host        | 10.223.224.185                   |
| redis_port        | 10544                            |
| redis_auth        | b988e9c27b52488c85b606201c647768 |
| redis_database    | 0                                |
+-------------------+----------------------------------+
```

Any idea where `tput: No value for $TERM and no -T specified` is coming from?

It goes away when I comment out `$formatter->display_item( $data );`

**Comment by danielbachhuber** [comment]
> Any idea where `tput: No value for $TERM and no -T` specified is coming from?

On a high-level, the error stems from the fact WP-CLI expects to either be run as TTY or piped. Terminus is opening an interactive session to Pantheon over SSH with pseudo-TTY disabled is an odd, in-between limbo state. Related: https://github.com/wp-cli/wp-cli/issues/2980

I believe this specific error is from a library WP-CLI depends on (https://github.com/wp-cli/php-cli-tools/blob/master/lib/cli/Shell.php#L41), and affects all use of WP-CLI on Pantheon.

In any regard, the problem isn't something specific to this pull request.

**Pull request merged**
