### PR TITLE
Ensure default cache group is always 'default'

### LINKED ISSUE #69: Ensure default cache group is always 'default'
The signature for `wp_cache_add()`:

```
function wp_cache_add( $key, $data, $group = '', $expire = 0 ) {`
```

The signature for `WP_Object_Cache->add()`:

```
public function add( $key, $data, $group = 'default', $expire = 0 ) {
```

WordPress core has the following within its methods so that `$group` is never empty:

```
if ( empty( $group ) )
	$group = 'default';
```

We, however, do not.

Related #68

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #69

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@joshkoenig #reviewmerge

**Comment by joshkoenig** [comment]
Just so I can be sure I understand:

1. When `USE_GROUPS` is `true` this will insure that if no `$group` is passed, we use a hash named `default` in redis. This prevents us from trying to use a hash named ''.

2. When `USE_GROUPS` is `false` this will insure that we always use keys like `default:{keyname}` in redis.

Is that correct? I want to be sure we are in line with the original objective from #68:

> However, when group=default in Redis, we may want to store these as top-level cache entries, instead of in the default group hash, because this will let us set expiry on the individual values.

**Comment by danielbachhuber** [comment]
> Just so I can be sure I understand:

Correct.

> However, when group=default in Redis, we may want to store these as top-level cache entries, 

On second thought, I don't think we should magically perform this behavior. Maybe something we can consider later if it comes up again, and there's a valid argument for.

**Comment by joshkoenig** [comment]
Ok good it is.

**Pull request merged**
