### PR TITLE
Fix hash sign comments

### PR DESCRIPTION
**Pull request by szepeviktor**
May it is more readable now

### CODE REVIEW

**Comment by szepeviktor** [comment]
@danielbachhuber I think we have a WPCS and a PHP vs. Redis error.

**Comment by szepeviktor** [comment]
Should I correct and mute WPCS errors?

**Comment by danielbachhuber** [comment]
> Should I correct and mute WPCS errors?

Please do.

For PHP 7 vs. Redis, I _think_ there's only an exception being thrown that needs to be caught with the test. I don't think it requires any functional changes to WP Redis.

**Comment by szepeviktor** [comment]
> Please do.

OK. Please merge this one.

**Comment by danielbachhuber** [comment]
Fixing these in #179

**Pull request closed without merging**
