### PR TITLE
Modern PHP versions for Travis

### LINKED ISSUE #241: Test Against PHP 7.3

### PR DESCRIPTION
**Pull request by szepeviktor**
https://www.php.net/supported-versions.php

Fixes #241

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @szepeviktor !

**Comment by szepeviktor** [comment]
:(

> ERROR: Looks like you're using PHPUnit 8.0.2. WordPress is currently only compatible with PHPUnit up to 7.x.

Seems like the build-in PHPUnit is more modern than it could be.

**Comment by szepeviktor** [comment]
@danielbachhuber It seem to pass 💚

**Comment by szepeviktor** [comment]
Oh no!! This is too high for old PHP.

**Comment by szepeviktor** [comment]
Done.

**Pull request merged**
