### PR TITLE
Continue supporting Redis v3

### PR DESCRIPTION
**Pull request by szepeviktor**
As Travis provides v4 by default

### CODE REVIEW

**Comment by szepeviktor** [comment]
Wait! Our boat is leaking.

**Comment by szepeviktor** [comment]
@danielbachhuber 🚢 is floating!

**Comment by danielbachhuber** [comment]
Awesome, thanks @szepeviktor. Closing in favor of #218 because I can't merge when Circle doesn't run:

image

**Comment by szepeviktor** [comment]
@danielbachhuber Maybe you or Pantheon is interested in running WordPress faster: autoloading core classes: https://github.com/szepeviktor/wordpress-autoloaded
What do you think, Daniel?

**Pull request closed without merging**
