### PR TITLE
Obey WPCS

### PR DESCRIPTION
**Pull request by szepeviktor**
From #177

### CODE REVIEW

**Comment by szepeviktor** [comment]
@danielbachhuber Hurray!

**Comment by danielbachhuber** [comment]
@szepeviktor I think the history is fine.

Can you fix the PHP 7 test issue in this PR too?

**Comment by szepeviktor** [comment]
Sorry. I am not into Redis testing.

**Comment by danielbachhuber** [comment]
Ok, no worries. Continuing on in #179

**Pull request closed without merging**
