### PR TITLE
Run tests on Trusty

### PR DESCRIPTION
**Pull request by szepeviktor**
which is also very old.

### CODE REVIEW

**Comment by szepeviktor** [comment]
CircleCI has some incorrect settings.

**Comment by danielbachhuber** [comment]
> CircleCI has some incorrect settings.

It's a private environment variable. I'll fix, two shakes.

**Comment by danielbachhuber** [comment]
@szepeviktor Can you merge `master` please?

**Comment by szepeviktor** [comment]
What happened?

**Comment by danielbachhuber** [comment]
> What happened?

Something faulty on Travis infrastructure probably.

**Pull request merged**
