### PR TITLE
Use in_array in wp_cache_supports

### PR DESCRIPTION
**Pull request by szepeviktor**
From  #378

### CODE REVIEW

**Comment by CdrMarks** [comment]
Hi Viktor, thanks for the PR.  We copied the function added in #378 from [WordPress core](https://github.com/WordPress/wordpress-develop/blob/832b6c35f36d5f1ca84feadc49b0e5424af0ad6c/src/wp-includes/cache.php#L314-327). 

Is there a performance benefit possible with this change?

**Comment by szepeviktor** [comment]
@CdrMarks All right. I'm not willing to push my agenda.
Has Daniel gone away?

BTW all code ending in return true/false shows a junior developer (to be polite)

**Comment by szepeviktor** [comment]
I'm sorry. I am used to "Thank you, Viktor" + merge.

**Comment by CdrMarks** [comment]
> Has Daniel gone away?
Correct; he's no longer working on Pantheon's plugins.

I'm going to close this for now.  Do let us know if you see any other issues.

**Comment by szepeviktor** [comment]
@CdrMarks 6 years of contribution has to stop. It is very sad.

**Comment by CdrMarks** [comment]
> It is very sad.

@ szepeviktor Yes it’s sad Daniel’s gone, but Pantheon now has a team dedicated to maintaining these plugins.

**Pull request closed without merging**
