### PR TITLE
Tweak initialization of the $wp_object_cache global

### PR DESCRIPTION
**Pull request by partounian**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
How does this fix the issue?

**Comment by partounian** [comment]
The original report stated 

> It looks like the global $wp_object_cache isn't set, aka its null when LudicrousDB tries to get something from the cache.

And then I copied these lines https://github.com/tillkruss/redis-cache/blob/68781b5b4cbd35c7eb2ca22d2d0db66ae57044fc/includes/object-cache.php#L180 as everything else seemed fine, and now it works for me.

Sorry for shoddy explanation, it just works for me :o

**Comment by danielbachhuber** [comment]
The test failure against `WP_VERSION=nightly` seems to be because the nightly build ZIP hasn't caught up to the SVN checkout. I'll ship this tomorrow after I get a passing build.

**Comment by danielbachhuber** [comment]
Just tagged the v0.7.1 release. Thanks again!

**Pull request merged**
