### PR TITLE
Properly handle exceptions thrown by PHPUnit to continue running tests

### PR DESCRIPTION
**Pull request by danielbachhuber**
Previously, the exception would be thrown and the test would pass without all of the assertions being run.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@joshkoenig #reviewmerge

**Comment by joshkoenig** [comment]
:+1:

**Comment by joshkoenig** [comment]
Looks like it needs a rebase though?

**Comment by danielbachhuber** [comment]
> Looks like it needs a rebase though?

Updated

**Pull request merged**
