### PR TITLE
Added redis tag

### PR DESCRIPTION
**Pull request by szepeviktor**
I was looking for this plugin and I could find it on WP.org.

### CODE REVIEW

**Comment by pantheon-circleci** [comment]
@szepeviktor, thanks for your PR! By analyzing the blame information on this pull request, we identified @danielbachhuber to be a potential reviewer

**Comment by szepeviktor** [comment]
@danielbachhuber Is there a blocking factor here?

**Comment by danielbachhuber** [comment]
> Is there a blocking factor here?

Nope — slipped my radar. Thanks!

**Comment by szepeviktor** [comment]
This is a useful feature.
At least for one man.

**Pull request merged**
