### PR TITLE
Catch Exceptions thrown during authentication

### LINKED ISSUE #34: There is nothing in place to catch the errors that don't fit in the retry_exception_messages
As of right now, if a RedisException is thrown which is not a `'wp_redis_retry_exception_messages'`, (see https://github.com/pantheon-systems/wp-redis/blob/master/object-cache.php#L749 ), then a fatal error will occur. Again, this is why this PR/Issue was created: https://github.com/pantheon-systems/wp-redis/pull/5

### PR DESCRIPTION
**Pull request by danielbachhuber**
This will let us more easily catch an Exception if there's an error
connecting.

Fixes #34

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Actually, I take that back. Once #40 is merged, I can write a test for failed authentication.

**Comment by jtsternberg** [comment]
Changing to this actually caused my error log to explode w/ these errors (repetitively):
```
[18-Nov-2015 15:38:17 UTC] WP Redis: Failed to AUTH connection
[18-Nov-2015 15:38:17 UTC] WP Redis: Failed to AUTH connection
[18-Nov-2015 15:38:17 UTC] WP Redis: Failed to AUTH connection
[18-Nov-2015 15:38:17 UTC] WP Redis: Failed to AUTH connection
[18-Nov-2015 15:38:17 UTC] PHP Warning:  WP Redis: read error on connection in D:\home\site\wwwroot\wp-content\plugins\wp-redis\object-cache.php on line 741
```

**Comment by danielbachhuber** [comment]
> Changing to this actually caused my error log to explode w/ these errors (repetitively):

Ah, because it tries to reconnect repeatedly.

**Comment by jtsternberg** [comment]
Actually, it may have to do w/ my tweaks to the file. I think the issue is that this error ("Failed to AUTH connection") is not in the `$retry_exception_messages` array, so it doesn't actually try to reconnect.

**Comment by jtsternberg** [comment]
Ok, it most definitely has to do with `$this->is_redis_connected` not yet being set when `$this->_call_redis( 'auth', $redis_server['auth'] );` is called. I think `$this->is_redis_connected` has to be set before AND after the auth call.

**Comment by danielbachhuber** [comment]
Failing test case looks like this:

```
salty-wordpress ➜  wp-redis  phpunit --filter test_redis_bad_authentication
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /srv/www/pantheon.dev/wp-content/plugins/wp-redis/phpunit.xml

E

Time: 2.31 seconds, Memory: 23.00Mb

There was 1 error:

1) CacheTest::test_redis_bad_authentication
RedisException: Redis server went away
```

**Pull request merged**
