### PR TITLE
Set type to wordpress-plugin

### PR DESCRIPTION
**Pull request by schrapel**
This allows us to include it in our composer.json.

### CODE REVIEW

**Comment by pantheon-circleci** [comment]
@schrapel, thanks for your PR! By analyzing the blame information on this pull request, we identified @danielbachhuber to be a potential reviewer

**Comment by danielbachhuber** [comment]
👍

**Comment by danielbachhuber** [comment]
@stevector Looks like our Terminus token stopped working here. Did it get removed from your account?

**Comment by stevector** [comment]
CircleCI won't supply the environmental variables to builds made from forks. I've moved this branch over to https://github.com/pantheon-systems/wp-redis/pull/114/files

**Comment by danielbachhuber** [comment]
> CircleCI won't supply the environmental variables to builds made from forks.

Oh, right. Should we have Circle bail if the machine token isn't present?

**Comment by stevector** [comment]
Yeah, probably.

**Pull request closed without merging**
